name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  github:
    needs:
      - docker
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - run: npm ci

      - run: node scripts/changelog.js > changelog.md

      - run: echo "TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Upload GitHub Release
        run: gh release create "$TAG" --title "$TAG" -F changelog.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docker:
    strategy:
      matrix:
        include:
          - job: web
            task: "build"
            image: bangumi/chii
            dockerfile: etc/Dockerfile
          - job: archive
            task: "build-archive"
            image: bangumi/chii-cmd-archive
            dockerfile: etc/archive.Dockerfile
          - job: canal
            task: "build-canal"
            image: bangumi/chii-canal
            dockerfile: etc/canal.Dockerfile

    name: "docker ${{ matrix.job }}"

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version-file: "go.mod"
          check-latest: true

      - name: Go Build Cache (build)
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg
          key: go-cache-119-${{ hashFiles('**/go.sum') }}-build
          restore-keys: |
            go-cache-119-${{ hashFiles('**/go.sum') }}-

      - run: echo "TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Install Task
        uses: arduino/setup-task@v1
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"

      - run: task ${{ matrix.task }}
        name: Build Binary

      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          context: ./
          file: ${{ matrix.dockerfile }}
          tags: ghcr.io/${{ matrix.image }}:latest,ghcr.io/${{ matrix.image }}:${{env.TAG}}
